timestamp: 1778734673.683
replicaCount: 3
image:
  repository: 519659321340.dkr.ecr.ap-south-1.amazonaws.com/docker/app-ui
  tag: 0.0.145
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ''
fullnameOverride: app-ui
serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: km-qa-app
    alb.ingress.kubernetes.io/group.order: '2'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:519659321340:certificate/ab1ca5a2-4e6d-40b3-849a-64c0d4ddc0c5
  hosts:
  - host: qa.app.kernelmind.ai
    paths:
    - path: /
      pathType: Prefix
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
