replicaCount: 2
image:
  repository: 210519480143.dkr.ecr.ap-south-1.amazonaws.com/docker/app-ui
  tag: 0.0.33
  pullPolicy: IfNotPresent
containerPort: 3000
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  className: alb
  host: qa.app.argusintelligence.net
  scheme: internet-facing
  targetType: ip
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: argus-qa-app
    alb.ingress.kubernetes.io/group.order: '2'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:210519480143:certificate/a9f7370b-c2a5-4e98-8f3a-e96470d1b028
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}
