replicaCount: 2

image:
  repository: <your-ecr-repo-url>/react-ui
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 3000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: alb
  host: ui.example.com  # <-- replace with your domain
  certificateArn: arn:aws:acm:ap-south-1:210519480143:certificate/xxxxxxxxxxxx
  scheme: internet-facing
  targetType: ip
  group:
    name: frontend-ingress-group
  annotations:
    # Required for AWS Load Balancer Controller
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: frontend-ingress-group
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:210519480143:certificate/xxxxxxxxxxxx

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
